### ISSUE TITLE
Why are the mismatched lines also green now, and how can I change this property

### ISSUE THREAD

**Issue by sukaixiong** [Vincentqyw/image-matching-webui#101]
Why are the mismatched lines also green now, and how can I change this property

**Comment by sukaixiong** [comment]
How can I restore the color of the matching lines to how they were last time? Thank you very much for your help.

**Comment by sukaixiong** [comment]
Have you updated and can you provide a version from a few months ago? Thank you very much

**Comment by Vincentqyw** [comment]
See more information here: https://github.com/Vincentqyw/image-matching-webui/issues/35#issuecomment-2393871218
