### ISSUE TITLE
where is the file "extra_utils/utils.py"?

### ISSUE THREAD

**Issue by msskaa12** [Vincentqyw/image-matching-webui#14]
after clone this repository , could not find the file .

model_zoo in file [extra_utils/utils.py](https://github.com/Vincentqyw/image-matching-webui/blob/main/extra_utils/utils.py).

**Comment by Vincentqyw** [comment]
I have updated `README`, please find `matcher_zoo` in `common/utils.py`: https://github.com/Vincentqyw/image-matching-webui/blob/bb2f1cb8a0ed1a248b26f29c7f2c781af5851831/common/utils.py#L437-L540
