### ISSUE TITLE
add SFD2 and IMP

### ISSUE THREAD

**Issue by feixue94** [Vincentqyw/image-matching-webui#17]
Excellent work! It would be great to compare the performance of different local features and matchers. 

Can I add the SFD2 - semantic local feature (https://github.com/feixue94/sfd2) and IMP - iterative matching matcher (https://github.com/feixue94/imp-release) to the repository?

**Comment by Vincentqyw** [comment]
Yes, of course! You can follow the instructions [here](https://github.com/Vincentqyw/image-matching-webui#add-your-own-feature--matcher) and submit a PR.

**Comment by Vincentqyw** [comment]
Closed! https://github.com/Vincentqyw/image-matching-webui/pull/40

**Comment by Vincentqyw** [comment]
For CPU CI reasons, reopen it. @feixue94, I have submitted a PR for CPU inference. Kindly review it at https://github.com/feixue94/pram/pull/2.

**Comment by feixue94** [comment]
Done. Thanks.
