### ISSUE TITLE
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody

### ISSUE THREAD

**Issue by KevenGe** [Vincentqyw/image-matching-webui#20]
I'm using Windows and WSL, but I keep getting this error and can't really get it to work.

How do I fix this error please?

![image](https://github.com/Vincentqyw/image-matching-webui/assets/49386259/5cb00de6-413f-4680-ac20-908b5f2d52e8)

```
Task exception was never retrieved
future: <Task finished name='j7l5nczw6pi_3' coro=<Queue.process_events() done, defined at /home/qf/miniconda3/envs/imw/lib/python3.10/site-packages/gradio/queueing.py:342> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['data:image/jpe...on_hash': 'j7l5nczw6pi'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing>
Traceback (most recent call last):
  File "/home/qf/miniconda3/envs/imw/lib/python3.10/site-packages/gradio/queueing.py", line 346, in process_events
    client_awake = await self.gather_event_data(event)
  File "/home/qf/miniconda3/envs/imw/lib/python3.10/site-packages/gradio/queueing.py", line 219, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/home/qf/miniconda3/envs/imw/lib/python3.10/site-packages/gradio/queueing.py", line 448, in get_message
    return PredictBody(**data), True
  File "/home/qf/miniconda3/envs/imw/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': ['data:image/jpe...on_hash': 'j7l5nczw6pi'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
```

**Comment by KevenGe** [comment]
Found the reason, it was caused by a low version of gradio. Not sure why, but after updating gradio to the latest version, the problem disappeared.

**Comment by Vincentqyw** [comment]
Great! By the way, which version of `gradio` did you encounter the issue with?

**Comment by KevenGe** [comment]
> Great! By the way, which version of `gradio` did you encounter the issue with?


The version information at the time of this problem is as follows

```
# gradio==3.35.2
# gradio_client==0.2.7
```

When I updated to the latest version, the problem disappeared!

```
# gradio==4.7.1
# gradio_client==0.7.0
```

I don't know why the problem occurred, but the update did fix the problem. The default version is 3.35.2 that the version may be outdated and it is recommended to test if the problem is actually there.

**Comment by Vincentqyw** [comment]
Fixed by update gradio: 
``` bash
pip install gradio>=4.12.0
```

**Comment by Bend1031** [comment]
> Fixed by updating gradio:
> 
> ```shell
> pip install gradio>=4.12.0
> ```

The same issue has been fixed after updating the version of the gradio, so could you update the gradio version in the requirements.txt ? Thanks❤
