### ISSUE TITLE
Running an error on Windows (both Win10 and 11 are)

### ISSUE THREAD

**Issue by heitieya** [Vincentqyw/image-matching-webui#21]
*** Aborted at 1707060306 (unix time) try "date -d @1707060306" if you are using GNU date ***
    @     0x7ffdc24f4090 log2f
    @     0x7ff7812c1f5c OPENSSL_Applink
    @     0x7ffdb903f73f __C_specific_handler
    @     0x7ffdc4b1441f __chkstk
    @     0x7ffdc4a8e466 RtlFindCharInUnicodeString
    @     0x7ffdc4b1340e KiUserExceptionDispatcher
    @     0x7ffd6e1f264e void __cdecl __ExceptionPtrRethrow(void const * __ptr64)
    @     0x7ffc2f2b38de public: void __cdecl c10::ivalue::Future::markCompleted(void) __ptr64
    @     0x7ffc2f531e19 struct _object * __ptr64 __cdecl THPGenerator_initDefaultGenerator(struct at::Generator)
    @     0x7ffc2a70dea5 (unknown)
    @     0x7ffc2ac66b29 PyInit_pycolmap
    @     0x7ffd9ade1080 (unknown)
    @     0x7ffd9ade2715 __NLG_Return2
    @     0x7ffdc4b13c66 RtlCaptureContext2
    @     0x7ffc2a7109b9 (unknown)
    @     0x7ffd5d49fd0d PyCFunction_GetFlags
    @     0x7ffd5d45acf8 _PyObject_MakeTpCall
    @     0x7ffd5d464141 PyComplex_AsCComplex
    @     0x7ffd5d4a43e4 _PyObject_GenericGetAttrWithDict
    @     0x7ffd5d4a3d18 PyObject_GetAttr
    @     0x7ffd5d4a3969 PyObject_GetAttrString
    @     0x7ffc2a74609e PyInit_pycolmap
    @     0x7ffc2a79dc6d PyInit_pycolmap
    @     0x7ffc2a77651d PyInit_pycolmap
    @     0x7ffc2a734170 (unknown)
    @     0x7ffc2a740a48 PyInit_pycolmap
    @     0x7ffc2a74054e PyInit_pycolmap
    @     0x7ffd5d5a0db9 PyImport_AppendInittab
    @     0x7ffd5d5a074c PyImport_Import
    @     0x7ffd5d49f919 PyCFunction_GetFlags
    @     0x7ffd5d56f8fc PyEval_GetFuncDesc
    @     0x7ffd5d56a720 _PyEval_EvalFrameDefault
    May I ask if you know the reason? Thank you very much

**Comment by Vincentqyw** [comment]
Please verify the versions of the packages that you have installed, with a particular focus on whether `pycolmap` has been installed successfully.

**Comment by osmancanaksoy** [comment]
I'm getting the same error too. My packages are installed correctly.

**Comment by heitieya** [comment]
> Please verify the versions of the packages that you have installed, with a particular focus on whether `pycolmap` has been installed successfully.
Yes, I have installed _pycolmap_ correctly and the environment still reports this error when running other code, which means the environment is completely obsolete. helpless
![image](https://github.com/Vincentqyw/image-matching-webui/assets/89898279/1bdd7183-ccb3-401b-b167-1e8e2f8bdcd2)

**Comment by heitieya** [comment]
> I'm getting the same error too. My packages are installed correctly.

Hello, have you resolved the issue? thanks

**Comment by osmancanaksoy** [comment]
> > I'm getting the same error too. My packages are installed correctly.
> 
> 
> 
> Hello, have you resolved the issue? thanks

No, unfortunately I couldn't solve it.

**Comment by heitieya** [comment]
> > > I'm getting the same error too. My packages are installed correctly.
> > 
> > 
> > Hello, have you resolved the issue? thanks
> 
> No, unfortunately I couldn't solve it.

OMG I feel like I have it figured out, please install pycolmap with this line: conda install -c conda-forge pycolmap

**Comment by heitieya** [comment]
> I'm getting the same error too. My packages are installed correctly.


> Please verify the versions of the packages that you have installed, with a particular focus on whether `pycolmap` has been installed successfully.

Thank you very much. It is indeed a problem with pycolmap. I have solved pycolmap using this command: conda install - c conda forge pycolma

**Comment by HongFaWan** [comment]
Now, even with this command: conda install - c conda forge pycolmap, pycolmap cannot be installed

**Comment by Vincentqyw** [comment]
> Now, even with this command: conda install - c conda forge pycolmap, pycolmap cannot be installed

@HongFaWan I think it's been fixed in this PR: https://github.com/Vincentqyw/image-matching-webui/pull/75.  Just update your torch version to 2.4.0
