### ISSUE TITLE
*** Aborted at 1711654442 (unix time) try "date -d @1711654442" if you are using GNU date ***

### ISSUE THREAD

**Issue by saba99** [Vincentqyw/image-matching-webui#24]
python app.py
*** Aborted at 1711654442 (unix time) try "date -d @1711654442" if you are using GNU date ***
    @     0x7ff8e89a0ef5 _seh_filter_exe
    @     0x7ff75abe1cfc (unknown)
    @     0x7ff8ca31ecd0 __C_specific_handler
    @     0x7ff8eae323af __chkstk
    @     0x7ff8eade14b4 RtlRaiseException
    @     0x7ff8eae30ebe KiUserExceptionDispatcher
    @     0x7ff8bf3f25ee void __cdecl __ExceptionPtrRethrow(void const * __ptr64)
    @     0x7ff85414135f (unknown)
    @     0x7ff85414393c (unknown)
    @     0x7ff84f92dea5 (unknown)
    @     0x7ff84fe86b29 PyInit_pycolmap
    @     0x7ff8c1171080 (unknown)
    @     0x7ff8c11726a5 __NLG_Return2
    @     0x7ff8eae31716 RtlCaptureContext2
    @     0x7ff84f9309b9 (unknown)
    @     0x7ff85660c24a PyObject_IsTrue
    @     0x7ff8565d60db _PyObject_MakeTpCall
    @     0x7ff856740045 _Py_gitversion
    @     0x7ff8565d946c _PyObject_GenericGetAttrWithDict
    @     0x7ff8565d8967 PyObject_GetAttr
    @     0x7ff856618831 PyObject_GetAttrString
    @     0x7ff84f96609e PyInit_pycolmap
    @     0x7ff84f9bdc6d PyInit_pycolmap
    @     0x7ff84f99651d PyInit_pycolmap
    @     0x7ff84f954170 (unknown)
    @     0x7ff84f960a48 PyInit_pycolmap
    @     0x7ff84f96054e PyInit_pycolmap
    @     0x7ff856692304 _Py_fopen_obj
    @     0x7ff856692519 _Py_fopen_obj
    @     0x7ff85669246d _Py_fopen_obj
    @     0x7ff8565e09d7 _Py_HashPointer
    @     0x7ff8566193b4 PyVectorcall_Call

**Comment by Vincentqyw** [comment]
It's a problem in the version of `pycolmap`, please try:  https://github.com/Vincentqyw/image-matching-webui/issues/21#issuecomment-1965707908

**Comment by Vincentqyw** [comment]
Please try with docker: 
``` bash
docker pull vincentqin/image-matching-webui:latest
docker run -it -p 7860:7860 vincentqin/image-matching-webui:latest python app.py --server_name "0.0.0.0" --server_port=7860
```
