### ISSUE TITLE
Latest docker container not working

### ISSUE THREAD

**Issue by EpipolarWagner** [Vincentqyw/image-matching-webui#33]
## 🐛 Bug Report
Latest docker container not working. app_class has a syntax error

## 🔬 How To Reproduce
docker pull vincentqin/image-matching-webui:latest
docker run -it -p 7860:7860 vincentqin/image-matching-webui:latest python app.py --server_name "0.0.0.0" --server_port=7860

Traceback (most recent call last):
  File "/code/app.py", line 3, in <module>
    from common.app_class import ImageMatchingApp
  File "/code/common/app_class.py", line 203
    pwith gr.Accordion("Supported Algorithms", open=False):
          ^^
SyntaxError: invalid syntax

### Environment

Ubunto 20.04
Python 3.10.14

**Comment by Vincentqyw** [comment]
Fixed! Please pull the latest docker image and try again. If everything is working fine, please close the issue.

![image](https://github.com/Vincentqyw/image-matching-webui/assets/18531182/8e69b84f-5376-4ccb-8007-a3c3934f1ff3)

**Comment by EpipolarWagner** [comment]
Works now, thanks!
