### ISSUE TITLE
two bugs

### ISSUE THREAD

**Issue by VEDFU** [Vincentqyw/image-matching-webui#34]
问题1：
https://github.com/Vincentqyw/image-matching-webui/blob/d97d9af34de2d8d704e19d82b0ea76387b1527cc/hloc/match_dense.py#L396-L397
这两行应该是 ：
"keypoints0": kpts0.cpu().numpy(),
"keypoints1": kpts1.cpu().numpy(),

问题2： 缺少 matchers/dedode.py 文件

**Comment by VEDFU** [comment]
> 问题1：
> 
> https://github.com/Vincentqyw/image-matching-webui/blob/d97d9af34de2d8d704e19d82b0ea76387b1527cc/hloc/match_dense.py#L396-L397
> 
> 
> 这两行应该是 ：
> "keypoints0": kpts0.cpu().numpy(),
> "keypoints1": kpts1.cpu().numpy(),
> 问题2： 缺少 matchers/dedode.py 文件

针对问题2：match_dense.py里面 dedode_sparse 用的是  extractors/dedode.py?

**Comment by Vincentqyw** [comment]
> 问题1：
> 
> https://github.com/Vincentqyw/image-matching-webui/blob/d97d9af34de2d8d704e19d82b0ea76387b1527cc/hloc/match_dense.py#L396-L397
> 
> 
> 这两行应该是 ：
> "keypoints0": kpts0.cpu().numpy(),
> "keypoints1": kpts1.cpu().numpy(),
> 问题2： 缺少 matchers/dedode.py 文件

1. Not a bug, please try again and check the visualization. The naming of `keypoints` may lead to ambiguity. These `keypoints` are used in the subsequent visualization stage, where they are plotted on the original image. Therefore, resizing the points is necessary. There are no abnormalities in this process.
2. Key `dedode_sparse` is not used, so there is no `matchers/dedode.py`. I will delete the key.

If there are no other issues, please close the question.

**Comment by VEDFU** [comment]
> > 问题1：
> > https://github.com/Vincentqyw/image-matching-webui/blob/d97d9af34de2d8d704e19d82b0ea76387b1527cc/hloc/match_dense.py#L396-L397
> > 
> > 这两行应该是 ：
> > "keypoints0": kpts0.cpu().numpy(),
> > "keypoints1": kpts1.cpu().numpy(),
> > 问题2： 缺少 matchers/dedode.py 文件
> 
> 1. Not a bug, please try again and check the visualization. The naming of `keypoints` may lead to ambiguity. These `keypoints` are used in the subsequent visualization stage, where they are plotted on the original image. Therefore, resizing the points is necessary. There are no abnormalities in this process.
> 2. Key `dedode_sparse` is not used, so there is no `matchers/dedode.py`. I will delete the key.
> 
> If there are no other issues, please close the question.

我是用image0/1和keypoints0/1可视化出来不一致，改之后才会一致。

我理解image0/1和keypoints0/1是对应的，都是scale之后的（带_orig后缀的是scale之前的）。按现在的写法，keypoints0和keypoints0_orig是一样的，都是keypoints0_orig（keypoints1_orig同理）

**Comment by Vincentqyw** [comment]
I appreciate your insight. To address potential ambiguity, I've enacted some modifications in the subsequent commit:

https://github.com/Vincentqyw/image-matching-webui/commit/9162a574ad17c4941a2e3e8195f7864957d53156#diff-cbb7e4425d46c92eae364a7c62a58ff478af1d596e191b331396de21ab66405fL396-R420

Some Notes:

| - | Image |Detected KeyPoints |Matched KeyPoints|
| ------- | ------- | ------- |------- |
| wo. scale | image0| keypoints0  | mkeypoints0 |
| w. scale (view in UI)| image0_orig| keypoints0 _orig | mkeypoints0_orig|
