### ISSUE TITLE
I want to ask about the meaning of red color and yellow color and green color of matching lines. Could you please explain it?

### ISSUE THREAD

**Issue by zzxyzz** [Vincentqyw/image-matching-webui#35]
## Checklist

- [ ] I've searched the project's [`issues`]

## ❓ Question

How can I [...]?

Is it possible to [...]?

**Comment by Vincentqyw** [comment]
The different colors of the lines represent varying confidence levels of feature matches. It is a pseudo-color, where the gradient from red to blue indicates decreasing confidence levels. In some cases, certain feature matches do not have a specific confidence, so a default value of 1 is used. Visually, these matches appear as red on the image.

**Comment by zzxyzz** [comment]
OK, I see, Thank you!


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vincentqyw/image-matching-webui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月25日(星期六) 晚上6:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vincentqyw/image-matching-webui] I want to ask about the meaning of red color and yellow color and green color of matching lines. Could you please explain it? (Issue #35)





 
The different colors of the lines represent varying confidence levels of feature matches. It is a pseudo-color, where the gradient from red to blue indicates decreasing confidence levels. In some cases, certain feature matches do not have a specific confidence, so a default value of 1 is used. Visually, these matches appear as red on the image.

**Comment by Vincentqyw** [comment]
Update: Green indicates good matches, while red indicates bad after the fix. See the details in this PR: https://github.com/Vincentqyw/image-matching-webui/pull/79 and in this issue: https://github.com/Vincentqyw/image-matching-webui/issues/78
