### ISSUE TITLE
I see the words "images name" in the left top corner of the matching results every time . Can I remove that? 

### ISSUE THREAD

**Issue by zzxyzz** [Vincentqyw/image-matching-webui#38]
Thanks.

**Comment by Vincentqyw** [comment]
Yes! I have removed the words: https://github.com/Vincentqyw/image-matching-webui/commit/2e0d00b4c2db3c8205a5d507e599ee1adec104d8

**Comment by zzxyzz** [comment]
Can I see the result of revision this time right now on huggingface platform？I seem not to see this. Does that mean that I must deploy the ui in my PC to use it (without the word "image name")?

**Comment by Vincentqyw** [comment]
Updated!
