### ISSUE TITLE
Can you output matching coordinates? Yes, thank you

### ISSUE THREAD

**Issue by wzj-888** [Vincentqyw/image-matching-webui#39]

**Comment by Vincentqyw** [comment]
I've added an `output.pkl` file to the UI, which stores image-matching results in this patch: https://github.com/Vincentqyw/image-matching-webui/commit/947d69b0592327a452603bf83e419b14b4be7fd3
You can reload the file with code:
``` python
import pickle
with open('output.pkl', 'rb') as f: 
    pred = pickle.load(f)
print(pred.keys())
```
![image](https://github.com/Vincentqyw/image-matching-webui/assets/18531182/1ce3a86e-4e85-4eeb-957f-e61fcd307f89)

**Comment by wzj-888** [comment]
wow thank you！！！What a great job you did!
