### ISSUE TITLE
Aborted at 1720503527 (unix time) try "date -d @1720503527" if you are using GNU date

### ISSUE THREAD

**Issue by qinxue123321** [Vincentqyw/image-matching-webui#44]
(imw) PS E:\image-matching-webui> python app.py
*** Aborted at 1720503527 (unix time) try "date -d @1720503527" if you are using GNU date ***
    @     0x7ff9fb010ef5 _seh_filter_exe                                                                         
    @     0x7ff7e7761f6c OPENSSL_Applink                                                                         
    @     0x7ff9d3dfe5cf __C_specific_handler                                                                    
    @     0x7ff9fd7d292f __chkstk                                                                                
    @     0x7ff9fd782554 RtlRaiseException                                                                       
    @     0x7ff9fd7d143e KiUserExceptionDispatcher                                                               
    @     0x7ff9877c264e void __cdecl __ExceptionPtrRethrow(void const * __ptr64)                                
    @     0x7ff91ea0939e public: void __cdecl c10::ivalue::Future::markCompleted(void) __ptr64                   
    @     0x7ff91eda0484 struct _object * __ptr64 __cdecl THPGenerator_initDefaultGenerator(struct at::Generator)
    @     0x7ff93476d6f5 (unknown)                                                                               
    @     0x7ff934c9fa39 PyInit_pycolmap                   
    hello Dear,  why this problem

**Comment by Vincentqyw** [comment]
Find solution here: https://github.com/Vincentqyw/image-matching-webui/issues/21#issuecomment-1965707908
or retry with docker:
``` bash 
docker pull vincentqin/image-matching-webui:latest
docker run -it -p 7860:7860 vincentqin/image-matching-webui:latest python app.py --server_name "0.0.0.0" --server_port=7860
```

**Comment by qinxue123321** [comment]
thanks

**Comment by qinxue123321** [comment]
Downloading: "https://raw.githubusercontent.com/cvlab-epfl/disk/master/depth-save.pth" to C:\Users\wqx/.cache\torch\hub\checkpoints\depth-save.pth
this  could not dowload. hello:

**Comment by Vincentqyw** [comment]
Please download it manually and place the checkpoints in the correct path.
