### ISSUE TITLE
AttributeError: module 'pycolmap' has no attribute 'Rigid3d'

### ISSUE THREAD

**Issue by ZFD1** [Vincentqyw/image-matching-webui#49]
Hi !
my environment :
win11
anaconda
python=3.10.4

firstly, my pycolmap version is 0.4.0, i meet this error, then, i uninstalled it and use conda install -c conda-forge pycolmap.
the pycolmap version is 3.10.0, also has this error. 

How can I slove it?

**Comment by Vincentqyw** [comment]
Please update pycolmap:
```
pip install pycolmap==0.6.1
```

**Comment by ZFD1** [comment]
thank you！It‘s ok
