### ISSUE TITLE
webcam

### ISSUE THREAD

**Issue by muchluv525** [Vincentqyw/image-matching-webui#51]
hellow,i want to know how to use my webcam ,i cant click  to my webcam

**Comment by Vincentqyw** [comment]
![image](https://github.com/user-attachments/assets/53f3f5c5-c4a7-44f5-ae2b-26e37a10cec9)

**Comment by muchluv525** [comment]
i tried it ,but it did not work

**Comment by Vincentqyw** [comment]
> i tried it ,but it did not work

I think it might be caused by the Gradio official API or some camera hardware permission issues.
