### ISSUE TITLE
about parameters for LoFTR

### ISSUE THREAD

**Issue by inyeopjang** [Vincentqyw/image-matching-webui#53]
## ❓ Question

Can I know all the parameter values for LoFTR algorithm including RANSAC?

Thank you

**Comment by Vincentqyw** [comment]
For `loftr`, find more information [here](https://github.com/Vincentqyw/image-matching-webui/blob/main/hloc/matchers/loftr.py)
For RANSAC settings, you can find it here:
![image](https://github.com/user-attachments/assets/536a3732-1234-4690-bf5f-9e631d13881a)
