### ISSUE TITLE
Inconsistent Prints

### ISSUE THREAD

**Issue by eyildiz-ugoe** [Vincentqyw/image-matching-webui#56]
## 🐛 Bug Report

Even though I set the `setting_geometry` parameter in config to `Fundamental`, I still see `Homography` in some terminal prints.

```
[2024/08/20 12:55:55 hloc INFO] ransac_method: CV2_USAC_MAGSAC, geometry_type: Fundamental
[2024/08/20 12:55:55 hloc INFO] ransac_method: CV2_USAC_MAGSAC, geometry_type: Homography
```

## 🔬 How To Reproduce

1. Set the parameter in config, and run `python test_app_cli.py`, which will run for all methods.

### Environment

- OS: Ubuntu22
- Python version, get it with: 3.10.10

## 📎 Additional context

relevant part of the config that matters:

```
  setting_threshold: 0.1
  max_keypoints: 2000
  keypoint_threshold: 0.05
  enable_ransac: true
  ransac_method: CV2_USAC_MAGSAC
  ransac_reproj_threshold: 8
  ransac_confidence: 0.999
  ransac_max_iter: 10000
  ransac_num_samples: 4
  match_threshold: 0.2
  setting_geometry: Fundamental
```

**Comment by Vincentqyw** [comment]
Not a bug, as both `H` and `F` are estimated and stored in state caches. For further information, refer to [#L582-L603](https://github.com/Vincentqyw/image-matching-webui/blob/main/ui/utils.py#L582-L603).
Within the UI configuration, Fundamental or Homography is solely utilized for image warping without the need for re-estimation.
