### ISSUE TITLE
XFeat + LighterGlue

### ISSUE THREAD

**Issue by guipotje** [Vincentqyw/image-matching-webui#67]
## 🚀 Feature Request

Hi, congratulations on the impressive demo with a great variety of models! Thanks for adding xfeat.

I believe it should be fairly simple to include xfeat along with lighterglue matching (a faster version of lightglue). I’ve provided an [example here](https://colab.research.google.com/github/verlab/accelerated_features/blob/main/notebooks/xfeat%2Blg_torch_hub.ipynb) -- it's quite straightforward using torchhub; you just need a recent version of Kornia. It would be cool to have this option in the webUI as well! :)

**Comment by Vincentqyw** [comment]
Thank you for the suggestion! Added xfeat+lighterglue in this PR: https://github.com/Vincentqyw/image-matching-webui/pull/68
