### ISSUE TITLE
LightGlue gives errors

### ISSUE THREAD

**Issue by mikkelmedm** [Vincentqyw/image-matching-webui#7]
Hello, and thanks for your great work!

I am having errors whenever trying to use any combination of LightGlue. 
I.e. 
File "/home/mikkel/image-matching-webui/hloc/matchers/../../third_party/LightGlue/lightglue/lightglue.py", line 349, in _forward
    kpts0_, kpts1_ = data0['keypoints'], data1['keypoints']
IndexError: too many indices for tensor of dimension 4

Hope you can help

**Comment by Vincentqyw** [comment]
Fixed! Pls try the latest commit.
![image](https://github.com/Vincentqyw/image-matching-webui/assets/18531182/aa54ada3-d60f-4612-8f3f-a2f6c9bc2b57)

**Comment by mikkelmedm** [comment]
Will test LightGlue now :)

**Comment by Vincentqyw** [comment]
> /third_party/DarkFeat/checkpoints/DarkFeat.pth

You can manually download [darknet model](https://drive.google.com/uc?id=1Thl6m8NcmQ7zSAF-1_xaFs3F4H8UU6HX&confirm=t) and put it to the folder `third_party/DarkFeat/checkpoints/`

**Comment by mikkelmedm** [comment]
![image](https://github.com/Vincentqyw/image-matching-webui/assets/38498170/e6cb9e43-2d38-4dba-b515-35974f0427f9)
