### ISSUE TITLE
Using Superpoint detections as anchors for LoFTR and Roma

### ISSUE THREAD

**Issue by HtutLynn** [Vincentqyw/image-matching-webui#70]
Hi, 

Thank you for amazing work!

I've been trying to test coarse + dense matching for reconstruction to do aachen benchmark. Since this codebase support lots of dense matching algorithms, I've been testing with it but I've been having lots of errors. 

Can you providence some guidance for this?

Best regards

**Comment by Vincentqyw** [comment]
Sure! Please share the error details here so I can understand what's wrong with the code.
