### ISSUE TITLE
Installation on Windows 10 fails with cudatoolkit=12.1

### ISSUE THREAD

**Issue by juergenboehm** [Vincentqyw/image-matching-webui#73]
## 🐛 Bug Report

The "conda env create" command fails as follows:

(test39) C:\Users\Boehm.J\Documents\Python\ImageWebUI\image-matching-webui>conda env create -f environment.yaml
Channels:
 - pytorch
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=12.1*

Current channels:

  - https://conda.anaconda.org/pytorch/win-64
  - https://conda.anaconda.org/conda-forge/win-64
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/msys2/win-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

## 🔬 How To Reproduce

Execute

git clone --recursive https://github.com/Vincentqyw/image-matching-webui.git
cd image-matching-webui

in a certain working directory. Then execute the problematic command shown in the beginning.

### Environment

Windows 10 64bit, Dell Precision 3551, 32 GB RAM, Quadro P620 compute capability 6.1, 
driver 537.77

Miniconda installed (conda 24.7.1)

**Comment by Vincentqyw** [comment]
Fix: https://github.com/Vincentqyw/image-matching-webui/pull/75, please try the new `environment.yaml`

**Comment by Vincentqyw** [comment]
The issue is closed for now. Reopen if needed.
