### ISSUE TITLE
Adding support for estimating stereo pair geometry

### ISSUE THREAD

**Issue by aelsaer** [Vincentqyw/image-matching-webui#8]
Congrats on the project. Recently I played with and I like it. What I found interesting is that it would be nice for someone to estimate a fundamental matrix or a homography between the two images thus I added the necessary functionalities leveraging OpenCV. If you find this useful please let me know.

![image](https://github.com/Vincentqyw/image-matching-webui/assets/9017630/31183f64-de10-48a2-8460-38272bf4791b)

**Comment by Vincentqyw** [comment]
Great! Geometry Information is very useful. Please submit a PR if possible :)

**Comment by aelsaer** [comment]
Hello @Vincentqyw, I am on it.

**Comment by Vincentqyw** [comment]
merged https://github.com/Vincentqyw/image-matching-webui/pull/9
