### ISSUE TITLE
运行API后，网页显示当前无法使用此页面 0.0.0.0 当前无法处理此请求。

### ISSUE THREAD

**Issue by llyyccccc** [Vincentqyw/image-matching-webui#87]
## 🔬 How To Reproduce

1. ...

### Environment

- OS: [e.g. Linux / Windows / macOS]
- Python version, get it with:

```bash
python --version
```

**Comment by Vincentqyw** [comment]
I am unable to reproduce this issue. Please provide more information.

**Comment by Vincentqyw** [comment]
Closing for now. Reopen if needed.

**Comment by llyyccccc** [comment]
(imw) E:\image-matching-webui-main>python -m api.server
D:\Anaconda\envs\imw\lib\site-packages\torch\cuda\__init__.py:128: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11050). Please update your GPU driver by downloading and installing a new v
ersion from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at C:\cb\pytorch_1
000000000000\work\c10\cuda\CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Loaded SuperPoint model
[2024/10/28 18:54:15 hloc INFO] Load SuperPoint model done.
INFO:     Started server process [17972]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
HTTP ERROR 502
